services:
  - type: web
    name: serenity-bot
    env: node
    plan: free
    buildCommand: npm install --build-from-source=sqlite3
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
